# espanso match file
matches:
  - trigger: ":kconf"
    replace: "kubectl --kubeconfig"
  - trigger: ":kpods"
    replace: "kubectl get pods"
  - trigger: ":kfpods"
    replace: "kubectl --kubeconfig $|$ get pods"
  - trigger: ":ksvc"
    replace: "kubectl get service"
  - trigger: ":kfsvc"
    replace: "kubectl --kubeconfig $|$ get service"
  - trigger: ":kflogs"
    replace: "kubectl --kubeconfig $|$ logs --tail=200 -f"
  - trigger: ":kdesc"
    replace: "kubectl describe"
  - trigger: ":hlist"
    replace: "helm --kubeconfig $|$ list"
  - trigger: ":gsite"
    replace: "site:*.$|$.com"
